<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ParentManagement.Application\ParentManagement.Application.csproj" />
    <ProjectReference Include="..\ParentManagement.Domain\ParentManagement.Domain.csproj" />
    <ProjectReference Include="..\ParentManagement.Infrastructure\ParentManagement.Infrastructure.csproj" />
  </ItemGroup>

</Project>
